export type User = {
  id: string;
  first_name: string;
  last_name: string;
  gender: string;
  date_of_birth: Date;
  email: string;
  email_verified_at: string | null;
  account_tier: {
    id: number;
    title: string;
    slug: string;
    daily_limit: number;
    transaction_limit: number;
    maximum_balance: number;
    created_at: string;
    updated_at: string;
    requires_bvn: boolean;
    requires_nin: boolean;
    requires_document_verification: boolean;
  };
  phone: string;
  phone_verified_at: string | null;
  avatar: string | null;
  address: string | null;
  fcm_token: string | null;
  qrcode: string | null;
  last_seen: string | null;
  status: string;
  created_at: Date;
  updated_at: Date;
  settings: {
    "notifications.events": boolean;
    "notifications.flight_booking": boolean;
    "notifications.gift_card": boolean;
    "preferences.theme": "dark" | "light" | "system";
  };
  permissions: string[];
  roles: string[];
};
